//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DBModelLib.Entities
{
    public class Food
    {
        public Food()
        {
            Inventars = new HashSet<Inventar>();
        }

        public virtual string Name { get; set; }

        public virtual int Id { get; set; }

        public virtual Messurement Messurement { get; set; }

        public virtual FoodSort FoodSort { get; set; }

        public virtual ICollection<Inventar> Inventars { get; set; }
    }
}