//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DBModelLib.Entities
{

    public class User
    {
        public virtual string Name { get; set; }

        public virtual string SurName { get; set; }

        public virtual string EMail { get; set; }

        public virtual DateTime Birthday { get; set; }

        public virtual string City { get; set; }

        public virtual int ZipCode { get; set; }

        public virtual string Street { get; set; }

        public virtual int Id { get; set; }

        public virtual string Nickname { get; set; }

        public virtual ICollection<Inventar> Inventars { get; set; }

        public virtual ICollection<User> Friendslist { get; set; }
    }
}